---
# make ansible play nice in a virtualenv
ansible_python_interpreter: python

provider:
  host: "{{ inventory_hostname }}"
  username: root
  password: 'Manasa123'
  authorize: yes
  auth_pass: '123456'
  transport: cli

eos_purge_vlan_trunk_groups: yes

eos_users:
  - name: superadmin
    encryption: md5
    secret: '$1$J0auuPhz$Pkr5NnHssW.Jqlk17Ylpk0'
    privilege: 15
    role: network-admin
  - name: simplebob
    nopassword: true
    privilege: 0
    role: network-operator

