- name: isis library test
  eos_isis_test:
    host: "{{ inventory_hostname }}"
    provider: "{{ provider }}"
    command: show isis summary
    isis_interface: 1
  register: result
- debug:
    var: result
